// stations.js
const stations = [
  { id: "N001", name: "Live News 24x7", state: "National" },
  { id: "N002", name: "Vividh Bharati", state: "National" },
  { id: "N003", name: "Raagam", state: "National" },
  { id: "A001", name: "AIR Sri Vijaya Puram", state: "Andaman and Nicobar Islands" },
  { id: "AP001", name: "AIR Anantapur", state: "Andhra Pradesh" },
  { id: "AP002", name: "AIR Kadapa", state: "Andhra Pradesh" },
  { id: "AP003", name: "AIR Kurnool", state: "Andhra Pradesh" },
  { id: "AP004", name: "AIR Markapur", state: "Andhra Pradesh" },
  { id: "AP005", name: "FM Simahapuri Nellore", state: "Andhra Pradesh" },
  { id: "AP006", name: "AIR Tirupati", state: "Andhra Pradesh" },
  { id: "AP007", name: "AIR Andhra Pradesh", state: "Andhra Pradesh" },
  { id: "AP008", name: "FM Rainbow Vijayawada", state: "Andhra Pradesh" },
  { id: "AP009", name: "VB Telugu Vijayawada", state: "Andhra Pradesh" },
  { id: "AP010", name: "AIR Visakhapatnam", state: "Andhra Pradesh" },
  { id: "AP011", name: "FM Rainbow Visakhapatnam", state: "Andhra Pradesh" },
  { id: "AR001", name: "AIR Itanagar", state: "Arunachal Pradesh" },
  { id: "AR002", name: "FM Arun Itanagar", state: "Arunachal Pradesh" },
  { id: "AR003", name: "AIR Pasighat", state: "Arunachal Pradesh" },
  { id: "AR004", name: "AIR Tawang", state: "Arunachal Pradesh" },
  { id: "AR005", name: "AIR Tezu", state: "Arunachal Pradesh" },
  { id: "AS001", name: "AIR Dibrugarh", state: "Assam" },
  { id: "AS002", name: "AIR Diphu", state: "Assam" },
  { id: "AS003", name: "AIR Guwahati Mahabahu", state: "Assam" },
  { id: "AS004", name: "AIR Guwahati Pragjyotishpur", state: "Assam" },
  { id: "AS005", name: "AIR Haflong", state: "Assam" },
  { id: "AS006", name: "AIR Jorhat", state: "Assam" },
  { id: "AS007", name: "AIR Kokrajhar", state: "Assam" },
  { id: "AS008", name: "AIR Nagaon", state: "Assam" },
  { id: "AS009", name: "AIR Silchar", state: "Assam" },
  { id: "AS010", name: "AIR Tezpur", state: "Assam" },
  { id: "B001", name: "AIR Bhagalpur", state: "Bihar" },
  { id: "B002", name: "AIR Darbhanga", state: "Bihar" },
  { id: "B003", name: "AIR Patna", state: "Bihar" },
  { id: "B004", name: "FM Rainbow Patna", state: "Bihar" },
  { id: "B005", name: "VBS Patna", state: "Bihar" },
  { id: "B006", name: "AIR Purnia Bihar", state: "Bihar" },
  { id: "B007", name: "AIR Sasaram", state: "Bihar" },
  { id: "CH001", name: "AIR Chandigarh", state: "Chandigarh" },
  { id: "C001", name: "AIR Ambikapur", state: "Chhattisgarh" },
  { id: "C002", name: "AIR Bilaspur", state: "Chhattisgarh" },
  { id: "C003", name: "AIR Jagdalpur", state: "Chhattisgarh" },
  { id: "C004", name: "AIR Raigarh", state: "Chhattisgarh" },
  { id: "C005", name: "AIR Chhattisgarh", state: "Chhattisgarh" },
  { id: "C006", name: "AIR FM Raipur", state: "Chhattisgarh" },
  { id: "C007", name: "AIR Saraipali", state: "Chhattisgarh" },
  { id: "DD001", name: "AIR Daman", state: "Daman and Diu" },
  { id: "FMG", name: "FM Gold Delhi", state: "Delhi" },
  { id: "FMR", name: "FM Rainbow Delhi", state: "Delhi" },
  { id: "INDRA", name: "Indraprastha", state: "Delhi" },
  { id: "VBSDELHI", name: "VBS Delhi", state: "Delhi" },
  { id: "AARA", name: "AIR Aaradhana", state: "Delhi" },
  { id: "GA001", name: "AIR Mhadei Panaji", state: "Goa" },
  { id: "GA002", name: "VBS Panaji", state: "Goa" },
  { id: "GA003", name: "FM Rainbow Goa", state: "Goa" },
  { id: "G001", name: "AIR Gujarati", state: "Gujarat" },
  { id: "G002", name: "VBS Ahmedabad", state: "Gujarat" },
  { id: "G003", name: "AIR Ahwa", state: "Gujarat" },
  { id: "G004", name: "AIR Bhuj", state: "Gujarat" },
  { id: "G005", name: "AIR Godhra", state: "Gujarat" },
  { id: "G006", name: "AIR Himmatnagar", state: "Gujarat" },
  { id: "G007", name: "AIR Rajkot", state: "Gujarat" },
  { id: "G008", name: "VBS Rajkot", state: "Gujarat" },
  { id: "G009", name: "AIR Surat", state: "Gujarat" },
  { id: "G010", name: "AIR Vadodara", state: "Gujarat" },
  { id: "HR001", name: "AIR Hisar", state: "Haryana" },
  { id: "HR002", name: "AIR Kurukshetra", state: "Haryana" },
  { id: "HR003", name: "AIR Rohtak", state: "Haryana" },
  { id: "H001", name: "AIR Dharamshala", state: "Himachal Pradesh" },
  { id: "H002", name: "AIR Hamirpur FM", state: "Himachal Pradesh" },
  { id: "H003", name: "AIR Shimla", state: "Himachal Pradesh" },
  { id: "H004", name: "AIR Shimla FM", state: "Himachal Pradesh" },
  { id: "JK001", name: "AIR Bhaderwah", state: "Jammu and Kashmir" },
  { id: "JK002", name: "AIR Jammu", state: "Jammu and Kashmir" },
  { id: "JK003", name: "AIR Kathua", state: "Jammu and Kashmir" },
  { id: "JK004", name: "AIR Srinagar", state: "Jammu and Kashmir" },
  { id: "J001", name: "AIR Chaibasa", state: "Jharkhand" },
  { id: "J002", name: "AIR Daltonganj", state: "Jharkhand" },
  { id: "J003", name: "AIR Hazaribagh", state: "Jharkhand" },
  { id: "J004", name: "AIR Jamshedpur", state: "Jharkhand" },
  { id: "J005", name: "VBS Jamshedpur", state: "Jharkhand" },
  { id: "J006", name: "AIR Ranchi", state: "Jharkhand" },
  { id: "J007", name: "FM Rainbow Ranchi", state: "Jharkhand" },
  { id: "J008", name: "VBS Ranchi", state: "Jharkhand" },
  { id: "K001", name: "AIR Bellari", state: "Karnataka" },
  { id: "K002", name: "AIR Karnataka", state: "Karnataka" },
  { id: "K003", name: "Amrutvarshini", state: "Karnataka" },
  { id: "K004", name: "Rainbow Kannada Kaamanbilu", state: "Karnataka" },
  { id: "K005", name: "VB KANNADA", state: "Karnataka" },
  { id: "K006", name: "AIR Bhadravati", state: "Karnataka" },
  { id: "K007", name: "AIR Bijapur", state: "Karnataka" },
  { id: "K008", name: "AIR Chitradurga", state: "Karnataka" },
  { id: "K009", name: "AIR Dharwad", state: "Karnataka" },
  { id: "K010", name: "AIR Kalaburgi", state: "Karnataka" },
  { id: "K011", name: "AIR Hassan", state: "Karnataka" },
  { id: "K012", name: "AIR Hospet", state: "Karnataka" },
  { id: "K013", name: "AIR Karwar", state: "Karnataka" },
  { id: "K014", name: "AIR Mysuru", state: "Karnataka" },
  { id: "K015", name: "AIR Mangalore", state: "Karnataka" },
  { id: "K016", name: "AIR Madikeri", state: "Karnataka" },
  { id: "K017", name: "AIR Raichur", state: "Karnataka" },
  { id: "KR001", name: "AIR Devikulam", state: "Kerala" },
  { id: "KR002", name: "AIR Kannur", state: "Kerala" },
  { id: "KR003", name: "FM Rainbow Kochi", state: "Kerala" },
  { id: "KR004", name: "AIR Kochi", state: "Kerala" },
  { id: "KR005", name: "AIR Calicut", state: "Kerala" },
  { id: "KR006", name: "AIR Kozhikode Real FM", state: "Kerala" },
  { id: "KR007", name: "AIR Manjeri", state: "Kerala" },
  { id: "KR008", name: "AIR Thrissur", state: "Kerala" },
  { id: "KR009", name: "AIR Kerala", state: "Kerala" },
  { id: "KR010", name: "VB MALAYALAM", state: "Kerala" },
  { id: "L001", name: "AIR Kargil", state: "Ladakh" },
  { id: "L002", name: "AIR Leh", state: "Ladakh" },
  { id: "LK001", name: "AIR Kavaratti", state: "Lakshadweep" },
  { id: "MP001", name: "AIR Balaghat", state: "Madhya Pradesh" },
  { id: "MP002", name: "AIR Betul", state: "Madhya Pradesh" },
  { id: "MP003", name: "AIR Bhopal", state: "Madhya Pradesh" },
  { id: "MP004", name: "VBS Bhopal", state: "Madhya Pradesh" },
  { id: "MP005", name: "AIR Chhatarpur", state: "Madhya Pradesh" },
  { id: "MP006", name: "AIR Chhindwara", state: "Madhya Pradesh" },
  { id: "MP007", name: "AIR Guna", state: "Madhya Pradesh" },
  { id: "MP008", name: "AIR Gwalior", state: "Madhya Pradesh" },
  { id: "MP009", name: "AIR Indore", state: "Madhya Pradesh" },
  { id: "MP010", name: "VBS Indore", state: "Madhya Pradesh" },
  { id: "MP011", name: "AIR Jabalpur", state: "Madhya Pradesh" },
  { id: "MP012", name: "AIR Jabalpur FM", state: "Madhya Pradesh" },
  { id: "MP013", name: "AIR Khandwa", state: "Madhya Pradesh" },
  { id: "MP014", name: "AIR Rewa", state: "Madhya Pradesh" },
  { id: "MP015", name: "AIR Sagar", state: "Madhya Pradesh" },
  { id: "MP016", name: "AIR Shahdol", state: "Madhya Pradesh" },
  { id: "MP017", name: "AIR Shivpuri", state: "Madhya Pradesh" },
  { id: "M001", name: "AIR Ahilyanagar", state: "Maharashtra" },
  { id: "M002", name: "AIR Akola", state: "Maharashtra" },
  { id: "M003", name: "AIR Amravati", state: "Maharashtra" },
  { id: "M004", name: "AIR Chhatrapati Sambhaji Nagar", state: "Maharashtra" },
  { id: "M005", name: "AIR Beed", state: "Maharashtra" },
  { id: "M006", name: "AIR Chandrapur", state: "Maharashtra" },
  { id: "M007", name: "AIR Dhule", state: "Maharashtra" },
  { id: "M008", name: "AIR Jalgaon", state: "Maharashtra" },
  { id: "M009", name: "AIR Kolhapur", state: "Maharashtra" },
  { id: "M010", name: "AIR Marathi Mumbai Asmita", state: "Maharashtra" },
  { id: "M011", name: "FM Gold Mumbai", state: "Maharashtra" },
  { id: "M012", name: "FM Rainbow Mumbai", state: "Maharashtra" },
  { id: "M013", name: "Samvadita Mumbai", state: "Maharashtra" },
  { id: "M014", name: "VBS Mumbai", state: "Maharashtra" },
  { id: "M015", name: "VBS Nagpur", state: "Maharashtra" },
  { id: "M016", name: "AIR Nagpur", state: "Maharashtra" },
  { id: "M017", name: "AIR Nanded", state: "Maharashtra" },
  { id: "M018", name: "AIR Nasik", state: "Maharashtra" },
  { id: "M019", name: "AIR Dharashiv", state: "Maharashtra" },
  { id: "M020", name: "AIR Parbhani", state: "Maharashtra" },
  { id: "M021", name: "AIR Pune", state: "Maharashtra" },
  { id: "M022", name: "AIR Pune FM", state: "Maharashtra" },
  { id: "M023", name: "AIR Ratnagiri", state: "Maharashtra" },
  { id: "M024", name: "AIR Sindhudurg", state: "Maharashtra" },
  { id: "M025", name: "AIR Sangli", state: "Maharashtra" },
  { id: "M026", name: "AIR Satara", state: "Maharashtra" },
  { id: "M027", name: "AIR Solapur", state: "Maharashtra" },
  { id: "M028", name: "AIR Yavatmal", state: "Maharashtra" },
  { id: "MN001", name: "AIR Churachandpur", state: "Manipur" },
  { id: "MN002", name: "AIR Imphal Kangla", state: "Manipur" },
  { id: "MN003", name: "AIR Imphal Sangai", state: "Manipur" },
  { id: "ML001", name: "AIR Jowai", state: "Meghalaya" },
  { id: "ML002", name: "AIR Shillong", state: "Meghalaya" },
  { id: "ML003", name: "FM Jongphi Shillong", state: "Meghalaya" },
  { id: "ML004", name: "AIR North East Livestream", state: "Meghalaya" },
  { id: "ML005", name: "AIR Tura", state: "Meghalaya" },
  { id: "MZ001", name: "AIR Aizawl", state: "Mizoram" },
  { id: "MZ002", name: "FM Zoawi Aizawl", state: "Mizoram" },
  { id: "MZ003", name: "AIR Lunglei", state: "Mizoram" },
  { id: "NG001", name: "AIR Mokokchung", state: "Nagaland" },
  { id: "NG002", name: "AIR Kohima", state: "Nagaland" },
  { id: "NG003", name: "FM Tragopan Kohima", state: "Nagaland" },
  { id: "O001", name: "AIR Baripada", state: "Odisha" },
  { id: "O002", name: "AIR Berhampur", state: "Odisha" },
  { id: "O003", name: "AIR Bhawanipatna", state: "Odisha" },
  { id: "O004", name: "AIR Balangir", state: "Odisha" },
  { id: "O005", name: "AIR Odia", state: "Odisha" },
  { id: "O006", name: "FM Rainbow Cuttack", state: "Odisha" },
  { id: "O007", name: "VBS Cuttack", state: "Odisha" },
  { id: "O008", name: "AIR Jeypore", state: "Odisha" },
  { id: "O009", name: "AIR Joranda", state: "Odisha" },
  { id: "O010", name: "AIR Keonjhar", state: "Odisha" },
  { id: "O011", name: "AIR Puri FM", state: "Odisha" },
  { id: "O012", name: "AIR Rourkela", state: "Odisha" },
  { id: "O014", name: "AIR Sambalpur", state: "Odisha" },
  { id: "P001", name: "AIR Karaikal", state: "Puducherry" },
  { id: "P002", name: "AIR Puducherry", state: "Puducherry" },
  { id: "P003", name: "FM Rainbow Puducherry", state: "Puducherry" },
  { id: "PJ001", name: "AIR Bhatinda", state: "Punjab" },
  { id: "PJ002", name: "AIR Punjabi", state: "Punjab" },
  { id: "PJ003", name: "FM Rainbow Jalandhar", state: "Punjab" },
  { id: "PJ004", name: "AIR Patiala", state: "Punjab" },
  { id: "R001", name: "AIR Alwar", state: "Rajasthan" },
  { id: "R002", name: "AIR Banswara", state: "Rajasthan" },
  { id: "R003", name: "AIR Barmer", state: "Rajasthan" },
  { id: "R004", name: "AIR Bikaner", state: "Rajasthan" },
  { id: "R005", name: "AIR Chittorgarh", state: "Rajasthan" },
  { id: "R006", name: "AIR Churu", state: "Rajasthan" },
  { id: "R007", name: "AIR Jaipur", state: "Rajasthan" },
  { id: "R008", name: "VBS Jaipur", state: "Rajasthan" },
  { id: "R009", name: "AIR Jaisalmer", state: "Rajasthan" },
  { id: "R010", name: "AIR Jhalawar", state: "Rajasthan" },
  { id: "R011", name: "AIR Jodhpur", state: "Rajasthan" },
  { id: "R012", name: "AIR Jodhpur Sun City FM", state: "Rajasthan" },
  { id: "R013", name: "AIR Kota", state: "Rajasthan" },
  { id: "R014", name: "AIR Mount Abu", state: "Rajasthan" },
  { id: "R015", name: "AIR Nagaur", state: "Rajasthan" },
  { id: "R016", name: "AIR Sawai Madhopur", state: "Rajasthan" },
  { id: "R017", name: "AIR Suratgarh", state: "Rajasthan" },
  { id: "R018", name: "AIR Udaipur", state: "Rajasthan" },
  { id: "R019", name: "AIR Udaipur FM Lake City", state: "Rajasthan" },
  { id: "S001", name: "AIR Gangtok", state: "Sikkim" },
  { id: "T001", name: "AIR Tamil Nadu", state: "Tamil Nadu" },
  { id: "T002", name: "FM Gold Chennai", state: "Tamil Nadu" },
  { id: "T003", name: "FM Rainbow Chennai", state: "Tamil Nadu" },
  { id: "T004", name: "VB Tamil Chennai", state: "Tamil Nadu" },
  { id: "T005", name: "AIR Coimbatore", state: "Tamil Nadu" },
  { id: "T006", name: "FM Rainbow Coimbatore", state: "Tamil Nadu" },
  { id: "T007", name: "AIR Dharmapuri", state: "Tamil Nadu" },
  { id: "T008", name: "AIR Kodaikanal", state: "Tamil Nadu" },
  { id: "T009", name: "AIR Madurai FM", state: "Tamil Nadu" },
  { id: "T0092", name: "AIR Madurai", state: "Tamil Nadu" },
  { id: "T010", name: "FM Nagercoil Kumari", state: "Tamil Nadu" },
  { id: "T011", name: "AIR Ooty", state: "Tamil Nadu" },
  { id: "T012", name: "AIR Tiruchirappalli", state: "Tamil Nadu" },
  { id: "T013", name: "AIR Tiruchirappalli FM", state: "Tamil Nadu" },
  { id: "T014", name: "AIR Tirunelveli", state: "Tamil Nadu" },
  { id: "T015", name: "FM Rainbow Tirunelveli", state: "Tamil Nadu" },
  { id: "T016", name: "AIR Tuticorin", state: "Tamil Nadu" },
  { id: "TG001", name: "AIR Adilabad", state: "Telangana" },
  { id: "TG002", name: "AIR Telangana", state: "Telangana" },
  { id: "TG003", name: "FM Rainbow Hyderabad", state: "Telangana" },
  { id: "TG004", name: "VB Telugu Hyderabad", state: "Telangana" },
  { id: "TG005", name: "AIR Kothagudem", state: "Telangana" },
  { id: "TG006", name: "AIR Nizamabad", state: "Telangana" },
  { id: "TG007", name: "AIR Warangal", state: "Telangana" },
  { id: "TR001", name: "AIR Agartala", state: "Tripura" },
  { id: "TR002", name: "FM Ujjayanta Agartala", state: "Tripura" },
  { id: "TR003", name: "AIR Belonia", state: "Tripura" },
  { id: "TR004", name: "AIR Kailashahar", state: "Tripura" },
  { id: "UK001", name: "AIR Almora", state: "Uttarakhand" },
  { id: "UK002", name: "AIR Dehradun", state: "Uttarakhand" },
  { id: "UK003", name: "AIR Pauri", state: "Uttarakhand" },
  { id: "U001", name: "AIR Agra", state: "Uttar Pradesh" },
  { id: "U002", name: "AIR Prayagraj", state: "Uttar Pradesh" },
  { id: "U003", name: "AIR Bareilly", state: "Uttar Pradesh" },
  { id: "U004", name: "AIR Ayodhya", state: "Uttar Pradesh" },
  { id: "U005", name: "AIR Gorakhpur", state: "Uttar Pradesh" },
  { id: "U006", name: "AIR Jhansi", state: "Uttar Pradesh" },
  { id: "U007", name: "AIR Kanpur", state: "Uttar Pradesh" },
  { id: "U008", name: "FM Rainbow Kanpur", state: "Uttar Pradesh" },
  { id: "U009", name: "AIR Lucknow", state: "Uttar Pradesh" },
  { id: "U010", name: "FM Rainbow Lucknow", state: "Uttar Pradesh" },
  { id: "U011", name: "AIR Mathura", state: "Uttar Pradesh" },
  { id: "U012", name: "AIR Najibabad", state: "Uttar Pradesh" },
  { id: "U013", name: "AIR Obra", state: "Uttar Pradesh" },
  { id: "U014", name: "AIR Rampur", state: "Uttar Pradesh" },
  { id: "U015", name: "AIR Varanasi", state: "Uttar Pradesh" },
  { id: "U016", name: "KumbhVani", state: "Uttar Pradesh" },
  { id: "W001", name: "AIR Bangla", state: "West Bengal" },
  { id: "W002", name: "AIR Kolkata Geetanjali", state: "West Bengal" },
  { id: "W003", name: "AIR Kolkata Sanchayita", state: "West Bengal" },
  { id: "W004", name: "FM Gold Kolkata", state: "West Bengal" },
  { id: "W005", name: "FM Rainbow Kolkata", state: "West Bengal" },
  { id: "W006", name: "VBS Kolkata", state: "West Bengal" },
  { id: "W007", name: "AIR Kurseong", state: "West Bengal" },
  { id: "W008", name: "AIR Murshidabad", state: "West Bengal" },
  { id: "W009", name: "AIR Shantiniketan", state: "West Bengal" },
  { id: "W010", name: "AIR Maitree", state: "West Bengal" },
  { id: "W011", name: "AIR Siliguri", state: "West Bengal" }
];
