// stations.js
const stations = [
  { id: "N001", name: "Live News 24x7", state: "National", logo: "https://ik.imagekit.io/sqt8ptw1k/airnews.jpg" },
  { id: "N002", name: "Vividh Bharati", state: "National", logo: "https://ik.imagekit.io/sqt8ptw1k/images.jpg" },
  { id: "N003", name: "Raagam", state: "National", logo: "https://ik.imagekit.io/sqt8ptw1k/images%20(1).jpg" },
  { id: "A001", name: "Akashvani Sri Vijaya Puram", state: "Andaman and Nicobar Islands", logo: "" },
  { id: "AP001", name: "Akashvani Anantapur", state: "Andhra Pradesh", logo: "" },
  { id: "AP002", name: "Akashvani Kadapa", state: "Andhra Pradesh", logo: "" },
  { id: "AP003", name: "Akashvani Kurnool", state: "Andhra Pradesh", logo: "" },
  { id: "AP004", name: "Akashvani Markapur", state: "Andhra Pradesh", logo: "" },
  { id: "AP005", name: "FM Simahapuri Nellore", state: "Andhra Pradesh", logo: "" },
  { id: "AP006", name: "Akashvani Tirupati", state: "Andhra Pradesh", logo: "" },
  { id: "AP007", name: "Akashvani Andhra Pradesh", state: "Andhra Pradesh", logo: "" },
  { id: "AP008", name: "FM Rainbow Vijayawada", state: "Andhra Pradesh", logo: "" },
  { id: "AP009", name: "VB Telugu Vijayawada", state: "Andhra Pradesh", logo: "" },
  { id: "AP010", name: "Akashvani Visakhapatnam", state: "Andhra Pradesh", logo: "" },
  { id: "AP011", name: "FM Rainbow Visakhapatnam", state: "Andhra Pradesh", logo: "" },
  { id: "AR001", name: "Akashvani Itanagar", state: "Arunachal Pradesh", logo: "" },
  { id: "AR002", name: "FM Arun Itanagar", state: "Arunachal Pradesh", logo: "" },
  { id: "AR003", name: "Akashvani Pasighat", state: "Arunachal Pradesh", logo: "" },
  { id: "AR004", name: "Akashvani Tawang", state: "Arunachal Pradesh", logo: "" },
  { id: "AR005", name: "Akashvani Tezu", state: "Arunachal Pradesh", logo: "" },
  { id: "AS001", name: "Akashvani Dibrugarh", state: "Assam", logo: "" },
  { id: "AS002", name: "Akashvani Diphu", state: "Assam", logo: "" },
  { id: "AS003", name: "Akashvani Guwahati Mahabahu", state: "Assam", logo: "" },
  { id: "AS004", name: "Akashvani Guwahati Pragjyotishpur", state: "Assam", logo: "" },
  { id: "AS005", name: "Akashvani Haflong", state: "Assam", logo: "" },
  { id: "AS006", name: "Akashvani Jorhat", state: "Assam", logo: "" },
  { id: "AS007", name: "Akashvani Kokrajhar", state: "Assam", logo: "" },
  { id: "AS008", name: "Akashvani Nagaon", state: "Assam", logo: "" },
  { id: "AS009", name: "Akashvani Silchar", state: "Assam", logo: "" },
  { id: "AS010", name: "Akashvani Tezpur", state: "Assam", logo: "" },
  { id: "B001", name: "Akashvani Bhagalpur", state: "Bihar", logo: "" },
  { id: "B002", name: "Akashvani Darbhanga", state: "Bihar", logo: "" },
  { id: "B003", name: "Akashvani Patna", state: "Bihar", logo: "" },
  { id: "B004", name: "FM Rainbow Patna", state: "Bihar", logo: "" },
  { id: "B005", name: "VBS Patna", state: "Bihar", logo: "" },
  { id: "B006", name: "Akashvani Purnia Bihar", state: "Bihar", logo: "" },
  { id: "B007", name: "Akashvani Sasaram", state: "Bihar", logo: "" },
  { id: "CH001", name: "Akashvani Chandigarh", state: "Chandigarh", logo: "" },
  { id: "C001", name: "Akashvani Ambikapur", state: "Chhattisgarh", logo: "" },
  { id: "C002", name: "Akashvani Bilaspur", state: "Chhattisgarh", logo: "" },
  { id: "C003", name: "Akashvani Jagdalpur", state: "Chhattisgarh", logo: "" },
  { id: "C004", name: "Akashvani Raigarh", state: "Chhattisgarh", logo: "" },
  { id: "C005", name: "Akashvani Chhattisgarh", state: "Chhattisgarh", logo: "" },
  { id: "C006", name: "Akashvani FM Raipur", state: "Chhattisgarh", logo: "" },
  { id: "C007", name: "Akashvani Saraipali", state: "Chhattisgarh", logo: "" },
  { id: "DD001", name: "Akashvani Daman", state: "Daman and Diu", logo: "" },
  { id: "FMG", name: "FM Gold Delhi", state: "Delhi", logo: "" },
  { id: "FMR", name: "FM Rainbow Delhi", state: "Delhi", logo: "" },
  { id: "INDRA", name: "Indraprastha", state: "Delhi", logo: "" },
  { id: "VBSDELHI", name: "VBS Delhi", state: "Delhi", logo: "" },
  { id: "AARA", name: "Akashvani Aaradhana", state: "Delhi", logo: "" },
  { id: "GA001", name: "Akashvani Mhadei Panaji", state: "Goa", logo: "" },
  { id: "GA002", name: "VBS Panaji", state: "Goa", logo: "" },
  { id: "GA003", name: "FM Rainbow Goa", state: "Goa", logo: "" },
  { id: "G001", name: "Akashwani Gujarati", state: "Gujarat", logo: "" },
  { id: "G002", name: "VBS Ahmedabad", state: "Gujarat", logo: "" },
  { id: "G003", name: "Akashvani Ahwa", state: "Gujarat", logo: "" },
  { id: "G004", name: "Akashvani Bhuj", state: "Gujarat", logo: "" },
  { id: "G005", name: "Akashvani Godhra", state: "Gujarat", logo: "" },
  { id: "G006", name: "Akashvani Himmatnagar", state: "Gujarat", logo: "" },
  { id: "G007", name: "Akashvani Rajkot", state: "Gujarat", logo: "" },
  { id: "G008", name: "VBS Rajkot", state: "Gujarat", logo: "" },
  { id: "G009", name: "Akashvani Surat", state: "Gujarat", logo: "" },
  { id: "G010", name: "Akashvani Vadodara", state: "Gujarat", logo: "" },
  { id: "HR001", name: "Akashvani Hisar", state: "Haryana", logo: "" },
  { id: "HR002", name: "Akashvani Kurukshetra", state: "Haryana", logo: "" },
  { id: "HR003", name: "Akashvani Rohtak", state: "Haryana", logo: "" },
  { id: "H001", name: "Akashvani Dharamshala", state: "Himachal Pradesh", logo: "" },
  { id: "H002", name: "Akashvani Hamirpur FM", state: "Himachal Pradesh", logo: "" },
  { id: "H003", name: "Akashvani Shimla", state: "Himachal Pradesh", logo: "" },
  { id: "H004", name: "Akashvani Shimla FM", state: "Himachal Pradesh", logo: "" },
  { id: "JK001", name: "Akashvani Bhaderwah", state: "Jammu and Kashmir", logo: "" },
  { id: "JK002", name: "Akashvani Jammu", state: "Jammu and Kashmir", logo: "" },
  { id: "JK003", name: "Akashvani Kathua", state: "Jammu and Kashmir", logo: "" },
  { id: "JK004", name: "Akashvani Srinagar", state: "Jammu and Kashmir", logo: "" },
  { id: "J001", name: "Akashvani Chaibasa", state: "Jharkhand", logo: "" },
  { id: "J002", name: "Akashvani Daltonganj", state: "Jharkhand", logo: "" },
  { id: "J003", name: "Akashvani Hazaribagh", state: "Jharkhand", logo: "" },
  { id: "J004", name: "Akashvani Jamshedpur", state: "Jharkhand", logo: "" },
  { id: "J005", name: "VBS Jamshedpur", state: "Jharkhand", logo: "" },
  { id: "J006", name: "Akashvani Ranchi", state: "Jharkhand", logo: "" },
  { id: "J007", name: "FM Rainbow Ranchi", state: "Jharkhand", logo: "" },
  { id: "J008", name: "VBS Ranchi", state: "Jharkhand", logo: "" },
  { id: "K001", name: "Akashvani Bellari", state: "Karnataka", logo: "" },
  { id: "K002", name: "Akashvani Karnataka", state: "Karnataka", logo: "" },
  { id: "K003", name: "Amrutvarshini", state: "Karnataka", logo: "" },
  { id: "K004", name: "Rainbow Kannada Kaamanbilu", state: "Karnataka", logo: "" },
  { id: "K005", name: "VB KANNADA", state: "Karnataka", logo: "" },
  { id: "K006", name: "Akashvani Bhadravati", state: "Karnataka", logo: "" },
  { id: "K007", name: "Akashvani Bijapur", state: "Karnataka", logo: "" },
  { id: "K008", name: "Akashvani Chitradurga", state: "Karnataka", logo: "" },
  { id: "K009", name: "Akashvani Dharwad", state: "Karnataka", logo: "" },
  { id: "K010", name: "Akashvani Kalaburgi", state: "Karnataka", logo: "" },
  { id: "K011", name: "Akashvani Hassan", state: "Karnataka", logo: "" },
  { id: "K012", name: "Akashvani Hospet", state: "Karnataka", logo: "" },
  { id: "K013", name: "Akashvani Karwar", state: "Karnataka", logo: "" },
  { id: "K014", name: "Akashvani Mysuru", state: "Karnataka", logo: "" },
  { id: "K015", name: "Akashvani Mangalore", state: "Karnataka", logo: "" },
  { id: "K016", name: "Akashvani Madikeri", state: "Karnataka", logo: "" },
  { id: "K017", name: "Akashvani Raichur", state: "Karnataka", logo: "" },
  { id: "KR001", name: "Akashvani Devikulam", state: "Kerala", logo: "" },
  { id: "KR002", name: "Akashvani Kannur", state: "Kerala", logo: "" },
  { id: "KR003", name: "FM Rainbow Kochi", state: "Kerala", logo: "" },
  { id: "KR004", name: "Akashvani Kochi", state: "Kerala", logo: "" },
  { id: "KR005", name: "Akashvani Calicut", state: "Kerala", logo: "" },
  { id: "KR006", name: "Akashvani Kozhikode Real FM", state: "Kerala", logo: "" },
  { id: "KR007", name: "Akashvani Manjeri", state: "Kerala", logo: "" },
  { id: "KR008", name: "Akashvani Thrissur", state: "Kerala", logo: "" },
  { id: "KR009", name: "Akashvani Kerala", state: "Kerala", logo: "" },
  { id: "KR010", name: "VB MALAYALAM", state: "Kerala", logo: "" },
  { id: "L001", name: "Akashvani Kargil", state: "Ladakh", logo: "" },
  { id: "L002", name: "Akashvani Leh", state: "Ladakh", logo: "" },
  { id: "LK001", name: "Akashvani Kavaratti", state: "Lakshadweep", logo: "" },
  { id: "MP001", name: "Akashvani Balaghat", state: "Madhya Pradesh", logo: "" },
  { id: "MP002", name: "Akashvani Betul", state: "Madhya Pradesh", logo: "" },
  { id: "MP003", name: "Akashvani Bhopal", state: "Madhya Pradesh", logo: "" },
  { id: "MP004", name: "VBS Bhopal", state: "Madhya Pradesh", logo: "" },
  { id: "MP005", name: "Akashvani Chhatarpur", state: "Madhya Pradesh", logo: "" },
  { id: "MP006", name: "Akashvani Chhindwara", state: "Madhya Pradesh", logo: "" },
  { id: "MP007", name: "Akashvani Guna", state: "Madhya Pradesh", logo: "" },
  { id: "MP008", name: "Akashvani Gwalior", state: "Madhya Pradesh", logo: "" },
  { id: "MP009", name: "Akashvani Indore", state: "Madhya Pradesh", logo: "" },
  { id: "MP010", name: "VBS Indore", state: "Madhya Pradesh", logo: "" },
  { id: "MP011", name: "Akashvani Jabalpur", state: "Madhya Pradesh", logo: "" },
  { id: "MP012", name: "Akashvani Jabalpur FM", state: "Madhya Pradesh", logo: "" },
  { id: "MP013", name: "Akashvani Khandwa", state: "Madhya Pradesh", logo: "" },
  { id: "MP014", name: "Akashvani Rewa", state: "Madhya Pradesh", logo: "" },
  { id: "MP015", name: "Akashvani Sagar", state: "Madhya Pradesh", logo: "" },
  { id: "MP016", name: "Akashvani Shahdol", state: "Madhya Pradesh", logo: "" },
  { id: "MP017", name: "Akashvani Shivpuri", state: "Madhya Pradesh", logo: "" },
  { id: "M001", name: "Akashvani Ahilyanagar", state: "Maharashtra", logo: "" },
  { id: "M002", name: "Akashvani Akola", state: "Maharashtra", logo: "" },
  { id: "M003", name: "Akashvani Amravati", state: "Maharashtra", logo: "" },
  { id: "M004", name: "Akashvani Chhatrapati Sambhaji Nagar", state: "Maharashtra", logo: "" },
  { id: "M005", name: "Akashvani Beed", state: "Maharashtra", logo: "" },
  { id: "M006", name: "Akashvani Chandrapur", state: "Maharashtra", logo: "" },
  { id: "M007", name: "Akashvani Dhule", state: "Maharashtra", logo: "" },
  { id: "M008", name: "Akashvani Jalgaon", state: "Maharashtra", logo: "" },
  { id: "M009", name: "Akashvani Kolhapur", state: "Maharashtra", logo: "" },
  { id: "M010", name: "Akashvani Marathi Mumbai Asmita", state: "Maharashtra", logo: "" },
  { id: "M011", name: "FM Gold Mumbai", state: "Maharashtra", logo: "" },
  { id: "M012", name: "FM Rainbow Mumbai", state: "Maharashtra", logo: "" },
  { id: "M013", name: "Samvadita Mumbai", state: "Maharashtra", logo: "" },
  { id: "M014", name: "VBS Mumbai", state: "Maharashtra", logo: "" },
  { id: "M015", name: "VBS Nagpur", state: "Maharashtra", logo: "" },
  { id: "M016", name: "Akashvani Nagpur", state: "Maharashtra", logo: "" },
  { id: "M017", name: "Akashvani Nanded", state: "Maharashtra", logo: "" },
  { id: "M018", name: "Akashvani Nasik", state: "Maharashtra", logo: "" },
  { id: "M019", name: "Akashvani Dharashiv", state: "Maharashtra", logo: "" },
  { id: "M020", name: "Akashvani Parbhani", state: "Maharashtra", logo: "" },
  { id: "M021", name: "Akashvani Pune", state: "Maharashtra", logo: "" },
  { id: "M022", name: "Akashvani Pune FM", state: "Maharashtra", logo: "" },
  { id: "M023", name: "Akashvani Ratnagiri", state: "Maharashtra", logo: "" },
  { id: "M024", name: "Akashvani Sindhudurg", state: "Maharashtra", logo: "" },
  { id: "M025", name: "Akashvani Sangli", state: "Maharashtra", logo: "" },
  { id: "M026", name: "Akashvani Satara", state: "Maharashtra", logo: "" },
  { id: "M027", name: "Akashvani Solapur", state: "Maharashtra", logo: "" },
  { id: "M028", name: "Akashvani Yavatmal", state: "Maharashtra", logo: "" },
  { id: "MN001", name: "Akashvani Churachandpur", state: "Manipur", logo: "" },
  { id: "MN002", name: "Akashvani Imphal Kangla", state: "Manipur", logo: "" },
  { id: "MN003", name: "Akashvani Imphal Sangai", state: "Manipur", logo: "" },
  { id: "ML001", name: "Akashvani Jowai", state: "Meghalaya", logo: "" },
  { id: "ML002", name: "Akashvani Shillong", state: "Meghalaya", logo: "" },
  { id: "ML003", name: "FM Jongphi Shillong", state: "Meghalaya", logo: "" },
  { id: "ML004", name: "Akashvani North East Livestream", state: "Meghalaya", logo: "" },
  { id: "ML005", name: "Akashvani Tura", state: "Meghalaya", logo: "" },
  { id: "MZ001", name: "Akashvani Aizawl", state: "Mizoram", logo: "" },
  { id: "MZ002", name: "FM Zoawi Aizawl", state: "Mizoram", logo: "" },
  { id: "MZ003", name: "Akashvani Lunglei", state: "Mizoram", logo: "" },
  { id: "NG001", name: "Akashvani Mokokchung", state: "Nagaland", logo: "" },
  { id: "NG002", name: "Akashvani Kohima", state: "Nagaland", logo: "" },
  { id: "NG003", name: "FM Tragopan Kohima", state: "Nagaland", logo: "" },
  { id: "O001", name: "Akashvani Baripada", state: "Odisha", logo: "" },
  { id: "O002", name: "Akashvani Berhampur", state: "Odisha", logo: "" },
  { id: "O003", name: "Akashvani Bhawanipatna", state: "Odisha", logo: "" },
  { id: "O004", name: "Akashvani Balangir", state: "Odisha", logo: "" },
  { id: "O005", name: "Akashvani Odia", state: "Odisha", logo: "" },
  { id: "O006", name: "FM Rainbow Cuttack", state: "Odisha", logo: "" },
  { id: "O007", name: "VBS Cuttack", state: "Odisha", logo: "" },
  { id: "O008", name: "Akashvani Jeypore", state: "Odisha", logo: "" },
  { id: "O009", name: "Akashvani Joranda", state: "Odisha", logo: "" },
  { id: "O010", name: "Akashvani Keonjhar", state: "Odisha", logo: "" },
  { id: "O011", name: "Akashvani Puri FM", state: "Odisha", logo: "" },
  { id: "O012", name: "Akashvani Rourkela", state: "Odisha", logo: "" },
  { id: "O013", name: "Akashvani Mahanadi Sambalpur", state: "Odisha", logo: "" },
  { id: "O014", name: "Akashvani Sambalpur", state: "Odisha", logo: "" },
  { id: "P001", name: "Akashvani Karaikal", state: "Puducherry", logo: "" },
  { id: "P002", name: "Akashvani Puducherry", state: "Puducherry", logo: "" },
  { id: "P003", name: "FM Rainbow Puducherry", state: "Puducherry", logo: "" },
  { id: "PJ001", name: "Akashvani Bhatinda", state: "Punjab", logo: "" },
  { id: "PJ002", name: "Akashvani Punjabi", state: "Punjab", logo: "" },
  { id: "PJ003", name: "FM Rainbow Jalandhar", state: "Punjab", logo: "" },
  { id: "PJ004", name: "Akashvani Patiala", state: "Punjab", logo: "" },
  { id: "R001", name: "Akashvani Alwar", state: "Rajasthan", logo: "" },
  { id: "R002", name: "Akashvani Banswara", state: "Rajasthan", logo: "" },
  { id: "R003", name: "Akashvani Barmer", state: "Rajasthan", logo: "" },
  { id: "R004", name: "Akashvani Bikaner", state: "Rajasthan", logo: "" },
  { id: "R005", name: "Akashvani Chittorgarh", state: "Rajasthan", logo: "" },
  { id: "R006", name: "Akashvani Churu", state: "Rajasthan", logo: "" },
  { id: "R007", name: "Akashvani Jaipur", state: "Rajasthan", logo: "" },
  { id: "R008", name: "VBS Jaipur", state: "Rajasthan", logo: "" },
  { id: "R009", name: "Akashvani Jaisalmer", state: "Rajasthan", logo: "" },
  { id: "R010", name: "Akashvani Jhalawar", state: "Rajasthan", logo: "" },
  { id: "R011", name: "Akashvani Jodhpur", state: "Rajasthan", logo: "" },
  { id: "R012", name: "Akashvani Jodhpur Sun City FM", state: "Rajasthan", logo: "" },
  { id: "R013", name: "Akashvani Kota", state: "Rajasthan", logo: "" },
  { id: "R014", name: "Akashvani Mount Abu", state: "Rajasthan", logo: "" },
  { id: "R015", name: "Akashvani Nagaur", state: "Rajasthan", logo: "" },
  { id: "R016", name: "Akashvani Sawai Madhopur", state: "Rajasthan", logo: "" },
  { id: "R017", name: "Akashvani Suratgarh", state: "Rajasthan", logo: "" },
  { id: "R018", name: "Akashvani Udaipur", state: "Rajasthan", logo: "" },
  { id: "R019", name: "Akashvani Udaipur FM Lake City", state: "Rajasthan", logo: "" },
  { id: "S001", name: "Akashvani Gangtok", state: "Sikkim", logo: "" },
  { id: "T001", name: "Akashvani Tamil Nadu", state: "Tamil Nadu", logo: "" },
  { id: "T002", name: "FM Gold Chennai", state: "Tamil Nadu", logo: "" },
  { id: "T003", name: "FM Rainbow Chennai", state: "Tamil Nadu", logo: "" },
  { id: "T004", name: "VB Tamil Chennai", state: "Tamil Nadu", logo: "" },
  { id: "T005", name: "Akashvani Coimbatore", state: "Tamil Nadu", logo: "" },
  { id: "T006", name: "FM Rainbow Coimbatore", state: "Tamil Nadu", logo: "" },
  { id: "T007", name: "Akashvani Dharmapuri", state: "Tamil Nadu", logo: "" },
  { id: "T008", name: "Akashvani Kodaikanal", state: "Tamil Nadu", logo: "" },
  { id: "T009", name: "Akashvani Madurai FM", state: "Tamil Nadu", logo: "" },
  { id: "T0092", name: "Akashvani Madurai", state: "Tamil Nadu", logo: "" },
  { id: "T010", name: "FM Nagercoil Kumari", state: "Tamil Nadu", logo: "" },
  { id: "T011", name: "Akashvani Ooty", state: "Tamil Nadu", logo: "" },
  { id: "T012", name: "Akashvani Tiruchirappalli", state: "Tamil Nadu", logo: "" },
  { id: "T013", name: "Akashvani Tiruchirappalli FM", state: "Tamil Nadu", logo: "" },
  { id: "T014", name: "Akashvani Tirunelveli", state: "Tamil Nadu", logo: "" },
  { id: "T015", name: "FM Rainbow Tirunelveli", state: "Tamil Nadu", logo: "" },
  { id: "T016", name: "Akashvani Tuticorin", state: "Tamil Nadu", logo: "" },
  { id: "TG001", name: "Akashvani Adilabad", state: "Telangana", logo: "" },
  { id: "TG002", name: "Akashvani Telangana", state: "Telangana", logo: "" },
  { id: "TG003", name: "FM Rainbow Hyderabad", state: "Telangana", logo: "" },
  { id: "TG004", name: "VB Telugu Hyderabad", state: "Telangana", logo: "" },
  { id: "TG005", name: "Akashvani Kothagudem", state: "Telangana", logo: "" },
  { id: "TG006", name: "Akashvani Nizamabad", state: "Telangana", logo: "" },
  { id: "TG007", name: "Akashvani Warangal", state: "Telangana", logo: "" },
  { id: "TR001", name: "Akashvani Agartala", state: "Tripura", logo: "" },
  { id: "TR002", name: "FM Ujjayanta Agartala", state: "Tripura", logo: "" },
  { id: "TR003", name: "Akashvani Belonia", state: "Tripura", logo: "" },
  { id: "TR004", name: "Akashvani Kailashahar", state: "Tripura", logo: "" },
  { id: "UK001", name: "Akashvani Almora", state: "Uttarakhand", logo: "" },
  { id: "UK002", name: "Akashvani Dehradun", state: "Uttarakhand", logo: "" },
  { id: "UK003", name: "Akashvani Pauri", state: "Uttarakhand", logo: "" },
  { id: "U001", name: "Akashvani Agra", state: "Uttar Pradesh", logo: "" },
  { id: "U002", name: "Akashvani Prayagraj", state: "Uttar Pradesh", logo: "" },
  { id: "U003", name: "Akashvani Bareilly", state: "Uttar Pradesh", logo: "" },
  { id: "U004", name: "Akashvani Ayodhya", state: "Uttar Pradesh", logo: "" },
  { id: "U005", name: "Akashvani Gorakhpur", state: "Uttar Pradesh", logo: "" },
  { id: "U006", name: "Akashvani Jhansi", state: "Uttar Pradesh", logo: "" },
  { id: "U007", name: "Akashvani Kanpur", state: "Uttar Pradesh", logo: "" },
  { id: "U008", name: "FM Rainbow Kanpur", state: "Uttar Pradesh", logo: "" },
  { id: "U009", name: "Akashvani Lucknow", state: "Uttar Pradesh", logo: "" },
  { id: "U010", name: "FM Rainbow Lucknow", state: "Uttar Pradesh", logo: "" },
  { id: "U011", name: "Akashvani Mathura", state: "Uttar Pradesh", logo: "" },
  { id: "U012", name: "Akashvani Najibabad", state: "Uttar Pradesh", logo: "" },
  { id: "U013", name: "Akashvani Obra", state: "Uttar Pradesh", logo: "" },
  { id: "U014", name: "Akashvani Rampur", state: "Uttar Pradesh", logo: "" },
  { id: "U015", name: "Akashvani Varanasi", state: "Uttar Pradesh", logo: "" },
  { id: "U016", name: "KumbhVani", state: "Uttar Pradesh", logo: "" },
  { id: "W001", name: "Akashvani Bangla", state: "West Bengal", logo: "" },
  { id: "W002", name: "Akashvani Kolkata Geetanjali", state: "West Bengal", logo: "" },
  { id: "W003", name: "Akashvani Kolkata Sanchayita", state: "West Bengal", logo: "" },
  { id: "W004", name: "FM Gold Kolkata", state: "West Bengal", logo: "" },
  { id: "W005", name: "FM Rainbow Kolkata", state: "West Bengal", logo: "" },
  { id: "W006", name: "VBS Kolkata", state: "West Bengal", logo: "" },
  { id: "W007", name: "Akashvani Kurseong", state: "West Bengal", logo: "" },
  { id: "W008", name: "Akashvani Murshidabad", state: "West Bengal", logo: "" },
  { id: "W009", name: "Akashvani Shantiniketan", state: "West Bengal", logo: "" },
  { id: "W010", name: "Akashvani Maitree", state: "West Bengal", logo: "" },
  { id: "W011", name: "Akashvani Siliguri", state: "West Bengal", logo: "" }
];
